apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: database-2.cdsqiswsqwpt.ap-south-1.rds.amazonaws.com
  DB_USER: admin
  DB_PASSWORD: kuslapur2026
  DB_NAME: mydb
