name: Deploy to EKS

on:
push:
branches: my-app-withsecreat

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
- name: Checkout
  uses: actions/checkout@v4

- name: Configure AWS
  uses: aws-actions/configure-aws-credentials@v4
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: ap-south-1

- name: Login to ECR
  run: |
    aws ecr get-login-password --region ap-south-1 \
    | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

- name: Build & Push
  run: |
    docker build -t my-app .
    docker tag my-app ${{ secrets.ECR_REPO }}:${{ github.sha }}
    docker push ${{ secrets.ECR_REPO }}:${{ github.sha }}

- name: Update kubeconfig
  run: |
    aws eks update-kubeconfig --name my-cluster --region ap-south-1

- name: Replace Image
  run: |
    sed -i "s|IMAGE_PLACEHOLDER|${{ secrets.ECR_REPO }}:${{ github.sha }}|g" k8s/deployment.yaml

- name: Deploy Secrets
  run: |
    kubectl apply -f k8s/external-secret.yaml

- name: Deploy App
  run: |
    kubectl apply -f k8s/deployment.yaml
    kubectl apply -f k8s/service.yaml
```

